from options import CONFIG

DEFAULT_W = 800
DEFAULT_H = 600
DEFAULT_FPS = 60

SCALE_FACTOR_X = 1
SCALE_FACTOR_Y = 1
SCALE_SPEED = 1

if CONFIG.contents[CONFIG.I_W] != DEFAULT_W:
    SCALE_FACTOR_X = CONFIG.contents[CONFIG.I_W]/DEFAULT_W

if CONFIG.contents[CONFIG.I_H] != DEFAULT_H:
    SCALE_FACTOR_Y = CONFIG.contents[CONFIG.I_H]/DEFAULT_H

if CONFIG.contents[CONFIG.FPS].value != DEFAULT_FPS:
    SCALE_SPEED = CONFIG.contents[CONFIG.FPS].value/DEFAULT_FPS